In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\saran\Desktop\Project 3\netflixData.csv")

In [3]:
df.head(5)

,Show Id,Title,Description,Director,Genres,Cast,Production Country,Release Date,Rating,Duration,Imdb Score,Content Type,Date Added
0,cc1b6ed9-cf9e-4057-8303-34577fb54477,(Un)Well,This docuseries takes a deep dive into the luc...,NaN,Reality TV,NaN,United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,NaN
1,e2ef4e91-fb25-42ab-b485-be8e3b23dedb,#Alive,"As a grisly virus rampages a city, a lone man ...",Cho Il,"Horror Movies, International Movies, Thrillers","Yoo Ah-in, Park Shin-hye",South Korea,2020.0,TV-MA,99 min,6.2/10,Movie,"September 8, 2020"
2,b01b73b7-81f6-47a7-86d8-acb63080d525,#AnneFrank - Parallel Stories,"Through her diary, Anne Frank's story is retol...","Sabina Fedeli, Anna Migotto","Documentaries, International Movies","Helen Mirren, Gengher Gatti",Italy,2019.0,TV-14,95 min,6.4/10,Movie,"July 1, 2020"
3,b6611af0-f53c-4a08-9ffa-9716dc57eb9c,#blackAF,Kenya Barris and his family navigate relations...,NaN,TV Comedies,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,2020.0,TV-MA,1 Season,6.6/10,TV Show,NaN
4,7f2d4170-bab8-4d75-adc2-197f7124c070,#cats_the_mewvie,This pawesome documentary explores how our fel...,Michael Margolis,"Documentaries, International Movies",NaN,Canada,2020.0,TV-14,90 min,5.1/10,Movie,"February 5, 2020"

In [4]:
df.tail(5)

,Show Id,Title,Description,Director,Genres,Cast,Production Country,Release Date,Rating,Duration,Imdb Score,Content Type,Date Added
5962,62b8b682-f191-4c10-aa04-32319329bd8d,الف مبروك,"On his wedding day, an arrogant, greedy accoun...",Ahmed Nader Galal,"Comedies, Dramas, International Movies","Ahmed Helmy, Laila Ezz El Arab, Mahmoud El Fis...",Egypt,2009.0,TV-14,115 min,7.4/10,Movie,"April 25, 2020"
5963,5bed77ab-5e31-4216-8b51-44c9a35442e6,دفعة القاهرة,A group of women leaves Kuwait to attend unive...,NaN,"International TV Shows, TV Dramas","Bashar al-Shatti, Fatima Al Safi, Maram Baloch...",NaN,2019.0,TV-14,1 Season,NaN,TV Show,NaN
5964,4661ec0c-8692-4661-bc76-a96412b311fd,海的儿子,"Two brothers start a new life in Singapore, wh...",NaN,"International TV Shows, TV Dramas","Li Nanxing, Christopher Lee, Jesseca Liu, Appl...",NaN,2016.0,TV-14,1 Season,NaN,TV Show,NaN
5965,145c93a7-1924-403c-a933-4ede8ad66f26,반드시 잡는다,After people in his town start turning up dead...,Hong-seon Kim,"Dramas, International Movies, Thrillers",Baek Yoon-sik,South Korea,2017.0,TV-MA,110 min,6.5/10,Movie,"February 28, 2018"
5966,d4613d34-cb71-4bd6-b570-fa857f02c44d,최강전사 미니특공대 : 영웅의 탄생,"Miniforce, a special task force of elite range...",Young Jun Lee,Children & Family Movies,"Um Sang-hyun, Yang Jeong-hwa, Jeon Tae-yeol, S...",NaN,2018.0,TV-Y7,68 min,4.7/10,Movie,"September 1, 2018"

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5967 entries, 0 to 5966
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Show Id             5967 non-null   object
 1   Title               5967 non-null   object
 2   Description         5967 non-null   object
 3   Director            3903 non-null   object
 4   Genres              5967 non-null   object
 5   Cast                5437 non-null   object
 6   Production Country  5408 non-null   object
 7   Release Date        5964 non-null   float64
 8   Rating              5963 non-null   object
 9   Duration            5964 non-null   object
 10  Imdb Score          5359 non-null   object
 11  Content Type        5967 non-null   object
 12  Date Added          4632 non-null   object
dtypes: float64(1), object(12)
memory usage: 606.2+ KB

In [6]:
df["Date Added"]=pd.to_datetime(df["Date Added"],errors="coerce")

In [7]:
df["Imdb Score"]=df["Imdb Score"].str.replace("/10","")
df["Imdb Score"]=pd.to_numeric(df["Imdb Score"])

In [8]:
df.rename(columns={"Release Date":"Release Year"},inplace=True)

In [9]:
df.isnull().sum()

Show Id                  0
Title                    0
Description              0
Director              2064
Genres                   0
Cast                   530
Production Country     559
Release Year             3
Rating                   4
Duration                 3
Imdb Score             608
Content Type             0
Date Added            1335
dtype: int64

In [10]:
missing_values=df.isnull().mean()*100
print(missing_values)

Show Id                0.000000
Title                  0.000000
Description            0.000000
Director              34.590246
Genres                 0.000000
Cast                   8.882185
Production Country     9.368192
Release Year           0.050277
Rating                 0.067035
Duration               0.050277
Imdb Score            10.189375
Content Type           0.000000
Date Added            22.373052
dtype: float64

In [11]:
string_fields=df.select_dtypes(include="object").columns
df[string_fields]=df[string_fields].fillna("Not Available")

In [12]:
duplicates=df.duplicated().sum()
print(duplicates)

0

In [13]:
df["Title"]=df["Title"].str.replace("#","")

In [14]:
df.columns=df.columns.str.lower().str.replace(" ","_")

In [15]:
df["release_year"]=df["release_year"].astype("Int64")

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5967 entries, 0 to 5966
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   show_id             5967 non-null   object
 1   title               5967 non-null   object
 2   description         5967 non-null   object
 3   director            5967 non-null   object
 4   genres              5967 non-null   object
 5   cast                5967 non-null   object
 6   production_country  5967 non-null   object
 7   release_year        5964 non-null   Int64
 8   rating              5967 non-null   object
 9   duration            5967 non-null   object
 10  imdb_score          5359 non-null   float64
 11  content_type        5967 non-null   object
 12  date_added          4632 non-null   datetime64[ns]
dtypes: Int64(1), datetime64[ns](1), float64(1), object(10)
memory usage: 612.0+ KB

In [17]:
df.head(5)

,show_id,title,description,director,genres,cast,production_country,release_year,rating,duration,imdb_score,content_type,date_added
0,cc1b6ed9-cf9e-4057-8303-34577fb54477,(Un)Well,This docuseries takes a deep dive into the luc...,Not Available,Reality TV,Not Available,United States,2020,TV-MA,1 Season,6.6,TV Show,NaT
1,e2ef4e91-fb25-42ab-b485-be8e3b23dedb,Alive,"As a grisly virus rampages a city, a lone man ...",Cho Il,"Horror Movies, International Movies, Thrillers","Yoo Ah-in, Park Shin-hye",South Korea,2020,TV-MA,99 min,6.2,Movie,2020-09-08
2,b01b73b7-81f6-47a7-86d8-acb63080d525,AnneFrank - Parallel Stories,"Through her diary, Anne Frank's story is retol...","Sabina Fedeli, Anna Migotto","Documentaries, International Movies","Helen Mirren, Gengher Gatti",Italy,2019,TV-14,95 min,6.4,Movie,2020-07-01
3,b6611af0-f53c-4a08-9ffa-9716dc57eb9c,blackAF,Kenya Barris and his family navigate relations...,Not Available,TV Comedies,"Kenya Barris, Rashida Jones, Iman Benson, Genn...",United States,2020,TV-MA,1 Season,6.6,TV Show,NaT
4,7f2d4170-bab8-4d75-adc2-197f7124c070,cats_the_mewvie,This pawesome documentary explores how our fel...,Michael Margolis,"Documentaries, International Movies",Not Available,Canada,2020,TV-14,90 min,5.1,Movie,2020-02-05

In [18]:
df.tail(5)

,show_id,title,description,director,genres,cast,production_country,release_year,rating,duration,imdb_score,content_type,date_added
5962,62b8b682-f191-4c10-aa04-32319329bd8d,الف مبروك,"On his wedding day, an arrogant, greedy accoun...",Ahmed Nader Galal,"Comedies, Dramas, International Movies","Ahmed Helmy, Laila Ezz El Arab, Mahmoud El Fis...",Egypt,2009,TV-14,115 min,7.4,Movie,2020-04-25
5963,5bed77ab-5e31-4216-8b51-44c9a35442e6,دفعة القاهرة,A group of women leaves Kuwait to attend unive...,Not Available,"International TV Shows, TV Dramas","Bashar al-Shatti, Fatima Al Safi, Maram Baloch...",Not Available,2019,TV-14,1 Season,NaN,TV Show,NaT
5964,4661ec0c-8692-4661-bc76-a96412b311fd,海的儿子,"Two brothers start a new life in Singapore, wh...",Not Available,"International TV Shows, TV Dramas","Li Nanxing, Christopher Lee, Jesseca Liu, Appl...",Not Available,2016,TV-14,1 Season,NaN,TV Show,NaT
5965,145c93a7-1924-403c-a933-4ede8ad66f26,반드시 잡는다,After people in his town start turning up dead...,Hong-seon Kim,"Dramas, International Movies, Thrillers",Baek Yoon-sik,South Korea,2017,TV-MA,110 min,6.5,Movie,2018-02-28
5966,d4613d34-cb71-4bd6-b570-fa857f02c44d,최강전사 미니특공대 : 영웅의 탄생,"Miniforce, a special task force of elite range...",Young Jun Lee,Children & Family Movies,"Um Sang-hyun, Yang Jeong-hwa, Jeon Tae-yeol, S...",Not Available,2018,TV-Y7,68 min,4.7,Movie,2018-09-01

In [19]:
df.to_csv("cleaned_netflix_dataset.csv",index=False)